### ISSUE TITLE
[Feature] Full-screen demo

### ISSUE THREAD

**Issue by semicolin** [ng-doc/ng-doc#84]
### Description

I have a component that needs to be rendered in the full browser window. It does not make sense to render it within the doc page. I would like to show the source code for the demo, along with a button to open the live demo.

### Proposed solution

Add a `fullscreen` option to `NgDocDemoActionOptions` that would render a button instead of the actual demo. Clicking the button would show the demo at full size (maybe in a new tab?).

### Alternatives considered

I'm currently using a wrapper component and a child route for the demo component, but the child route broke with the switch to standalone page components. Adding a `routes` property to `NgDocPage` would fix my hacky solution, but I would prefer a built-in feature for full-screen demos.

**Comment by skoropadas** [comment]
Hey, sorry for the silence, I've been quite busy lately. Regarding the feature:

I see two options here:
- Create a truly FullScreen opening option that would open the demo in fullscreen mode within the same browser tab.
- The second option could be to open the demo in a new browser tab. In this case, you could pass the demo code using the `files` property, which was discussed in another ticket. The demo component itself would contain a button that, when clicked, would open the new tab of the browser. So, the implementation of that functionality would be up to you, and the demo would simply display the code of another component, which would be shown in the new browser tab.

**Comment by skoropadas** [comment]
@semicolin Hey, yesterday I released a new version that allows loading [files as snippets](https://ng-doc.com/docs/guides/snippets#loading-snippet-from-file). Could you take a look to see if this helps you achieve what you want?

In my understanding, you should create a component that will contain a button. Upon clicking the button, you will be able to open the component you need in a new tab. The demo code can be replaced with the component code in the new tab using file snippets.

**Comment by semicolin** [comment]
This is a nice feature and it will help eliminate a bit of trickery that was needed to combine the button and the demo in the same component. However, I still have the problem of defining a route for the real demo component because I can no longer define a child route in the page's module.

**Comment by skoropadas** [comment]
@semicolin with the last version you can! The `route` property of the page config was extended, now you can provide the route configuration for the page

**Comment by semicolin** [comment]
oh, nice! I'll give it a try.

**Comment by skoropadas** [comment]
@semicolin have you had time to try? Is this issue still relevant?

**Comment by semicolin** [comment]
I tried setting `route` property to a Route with children, but it does not work. I tried both `children` and `loadChildren`, standalone and module. Still trying to figure out why it doesn't work.

**Comment by skoropadas** [comment]
@semicolin thanks for the feedback I'll check it!

**Comment by skoropadas** [comment]
@semicolin Hey, I've been thinking about this issue lately, and you're right. A child route for configuring the page won't help achieve a fullscreen mode for the demo because it would still have a header, sidebar, and other parent elements provided by the parent route. To implement such a mode, you would need to create a separate route at the root of the application to get rid of parent elements like the header. However, this would create the inconvenience of manually setting up a separate route for each demo you want to have in fullscreen mode.

But we have two other options that are more dynamic and won't require additional actions from you:

1. As mentioned earlier, I could open a fullscreen modal that displays the demo.
2. We can utilize the browser's API and implement a proper fullscreen mode using `requestFullscreen`, not just for the component displayed in the demo but for the entire demo, including code examples. This way, users can simultaneously view the code and the result.

**Comment by semicolin** [comment]
A full-page modal has the advantage that the user can switch to other windows/tabs without closing it. But the disadvantage is that if it's full-page there's no way to close it unless it is a separate route so they can use the back button or open it in a separate tab.

**Comment by skoropadas** [comment]
@semicolin hey, sorry for the delay, finally found time and a more or less convenient way to create such demos, I will release a version now
